openapi: 3.0.0
info:
  title: Game API- Gateway 
  version: 1.0.0


paths:
  /register:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                pw:
                  type: string
              required:
                - username
                - email
                - pw
      responses:
        '200':
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                pw:
                  type: string
              required:
                - email
                - pw
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /joinmatch:
    post:
      summary: Play a match with creatures
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cr1:
                  type: string
                cr2:
                  type: string
                cr3:
                  type: string
                cr4:
                  type: string
                cr5:
                  type: string
              required:
                - cr1
                - cr2
                - cr3
                - cr4
                - cr5
      responses:
        '200':
          description: Match played successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /getAllResults:
    get:
      summary: Get all match results
      responses:
        '200':
          description: List of all matches
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                    # Define the properties of a match result here
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /getResults:
    get:
      summary: Get the last match results
      responses:
        '200':
          description: Last match results
          content:
            application/json:
              schema:
                type: object
                # Define the properties of the last match result here
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string


  /getPlayer:
    get:
      summary: Get player information
      responses:
        '200':
          description: Player information
          content:
            application/json:
              schema:
                type: object
                # Define the properties of the player information here
        '401':
          description: User is not authenticated
  /player:
    get:
      summary: Get all players info
      responses:
        '200':
          description: Retrieves a list of all players
          content:
            application/json:
              schema:
                type: object
                # Define the properties of the player information here
        '401':
          description: User is not authenticated

  /getCoins:
    get:
      summary: Get player's coins
      responses:
        '200':
          description: Player's coin count
          content:
            application/json:
              schema:
                type: object
                properties:
                  Coins:
                    type: number
        '401':
          description: User is not authenticated


  /creatures:
    get:
      summary: Get player's creatures
      responses:
        '200':
          description: List of player's creatures
          content:
            application/json:
              schema:
                type: object
                properties:
                  Creatures:
                    type: array
        '401':
          description: User is not authenticated
