openapi: 3.0.0
info:
  title: Match API
  version: 1.0.0
  description: API for handling match-related operations
paths:
  /playMatch:
    post:
      summary: Play a match
      operationId: playMatch
      responses:
        '200':
          description: Match played successfully
        '400':
          description: Error playing the match

  /getAllResults:
    get:
      summary: Get all match results
      operationId: getAllMatches
      responses:
        '200':
          description: Successfully retrieved all match results
        '404':
          description: No matches found

  /getResults:
    get:
      summary: Get last match results
      operationId: getLastMatches
      responses:
        '200':
          description: Successfully retrieved last match results
        '40
